-- MySQL Script generated by MySQL Workbench
-- Thu Mar 26 17:18:47 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_helpdesk
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_helpdesk` ;

-- -----------------------------------------------------
-- Schema db_helpdesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_helpdesk` DEFAULT CHARACTER SET utf8 ;
USE `db_helpdesk` ;

-- -----------------------------------------------------
-- Table `db_helpdesk`.`departaments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`departaments` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`departaments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`users` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `departament_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL,
  `is_active` TINYINT(1) NULL,
  `remember_token` VARCHAR(100) NULL,
  `role` ENUM('admin', 'técnico', 'usuario') NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `users_departament_id_foreign` (`departament_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `users_departament_id_foreign`
    FOREIGN KEY (`departament_id`)
    REFERENCES `db_helpdesk`.`departaments` (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`system_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`system_logs` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`system_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `module` VARCHAR(255) NOT NULL,
  `action` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `system_logs_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `system_logs_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_helpdesk`.`users` (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`priorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`priorities` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`priorities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `response_time` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `udpated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`categories` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`statuses` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`statuses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `color` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`tickets` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`tickets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `assigned_to` BIGINT UNSIGNED NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `status_id` BIGINT UNSIGNED NOT NULL,
  `priority_id` BIGINT UNSIGNED NOT NULL,
  `category_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `closed_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `tickets_priority_id_foreign` (`priority_id` ASC),
  INDEX `tickets_category_id_foreign` (`category_id` ASC),
  INDEX `tickets_user_id_foreign` (`user_id` ASC),
  INDEX `tickets_status_id_foreign` (`status_id` ASC),
  INDEX `tickets_assigned_to_id_foreign_idx` (`assigned_to` ASC),
  CONSTRAINT `tickets_priority_id_foreign`
    FOREIGN KEY (`priority_id`)
    REFERENCES `db_helpdesk`.`priorities` (`id`),
  CONSTRAINT `tickets_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_helpdesk`.`categories` (`id`),
  CONSTRAINT `tickets_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_helpdesk`.`users` (`id`),
  CONSTRAINT `tickets_status_id_foreign`
    FOREIGN KEY (`status_id`)
    REFERENCES `db_helpdesk`.`statuses` (`id`),
  CONSTRAINT `tickets_assigned_to_id_foreign`
    FOREIGN KEY (`assigned_to`)
    REFERENCES `db_helpdesk`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `db_helpdesk`.`ticket_attachments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`ticket_attachments` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`ticket_attachments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_id` BIGINT UNSIGNED NOT NULL,
  `original_name` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `file_size` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `attachments_ticket_ticket_id_foreign` (`ticket_id` ASC),
  CONSTRAINT `attachments_ticket_ticket_id_foreign`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `db_helpdesk`.`tickets` (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`ticket_messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`ticket_messages` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`ticket_messages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticted_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `message` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `ticket_messages_ticted_id_foreign` (`ticted_id` ASC),
  INDEX `ticket_messages_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `ticket_messages_ticted_id_foreign`
    FOREIGN KEY (`ticted_id`)
    REFERENCES `db_helpdesk`.`tickets` (`id`),
  CONSTRAINT `ticket_messages_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_helpdesk`.`users` (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`message_attachments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`message_attachments` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`message_attachments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_message_id` BIGINT UNSIGNED NOT NULL,
  `original_name` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `file_size` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `attachments_message_ticket_message_id_foreign` (`ticket_message_id` ASC),
  CONSTRAINT `attachments_message_ticket_message_id_foreign`
    FOREIGN KEY (`ticket_message_id`)
    REFERENCES `db_helpdesk`.`ticket_messages` (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`ticket_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`ticket_logs` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`ticket_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `action` VARCHAR(150) NOT NULL,
  `description` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `logs_ticket_id_foreign` (`ticket_id` ASC),
  INDEX `logs_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `logs_ticket_id_foreign`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `db_helpdesk`.`tickets` (`id`),
  CONSTRAINT `logs_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_helpdesk`.`users` (`id`));


-- -----------------------------------------------------
-- Table `db_helpdesk`.`faqs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_helpdesk`.`faqs` ;

CREATE TABLE IF NOT EXISTS `db_helpdesk`.`faqs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `answer` TEXT NOT NULL,
  `upedated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
